#$Id$

LF_OBJ=exopen.$(O) sublib.$(O) acommon.$(O) mcommon.$(O) authenticate.$(O) \
 lastdirsep.$(O)

all:	$(BINSS)

make:							# fake target
	@$(SHELL) -c "exit 0"

.PRECIOUS: Makefile

lockfile: lockfile.$(O) $(LF_OBJ)
	$(CC) $(CFLAGS) $@.$(O) $(LF_OBJ) -o $@ $(LDFLAGS)
	@test -z "$(STRIP)" || ( echo $(STRIP) $@; $(STRIP) $@ )

../config.check:
	@cd ..; $(MAKE) config.check

_autotst: _autotst.$(O) sublib.c sublib.h
	$(CC) $(CFLAGS) $@.$(O) -o $@ $(LDFLAGS)

../autoconf.h: autoconf Makefile ../patchlevel.h
	@echo No this was not make -n >make_n
	$(SHELL) ./autoconf $(SHELL) "$(RM)" "$(MV)" $(DEVNULL) \
 "$(FGREP)" "$(MAKE)" $(O) "$(LOCKINGTEST)" \
 "$(VISIBLE_BINDIR)" $@

autoconf.h: ../autoconf.h

acommon.$(O): ../autoconf.h ../config.h includes.h acommon.h robust.h shell.h

authenticate.$(O): ../autoconf.h ../config.h includes.h robust.h shell.h
authenticate.$(O): misc.h authenticate.h authenticate.c
	$(CC) -c -DPROCMAIL $(CFLAGS) $*.c

exopen.$(O): ../autoconf.h ../config.h includes.h procmail.h acommon.h robust.h
exopen.$(O): misc.h exopen.h

lastdirsep.$(O): ../autoconf.h ../config.h includes.h lastdirsep.h

lockfile.$(O): ../autoconf.h ../config.h includes.h sublib.h exopen.h mcommon.h
lockfile.$(O): authenticate.h ../patchlevel.h

mcommon.$(O): ../autoconf.h ../config.h includes.h mcommon.h

sublib.$(O): ../autoconf.h ../config.h includes.h sublib.h shell.h

.c.$(O):
	$(CC) -c $(CFLAGS) $<

../man/man.sed: manconf.c ../autoconf.h ../config.h includes.h procmail.h
../man/man.sed: ../patchlevel.h
	@$(CC) $(CFLAGS) "-DBINDIR=\"$(VISIBLE_BINDIR)\"" -o _autotst \
 manconf.c $(LDFLAGS)
	@./_autotst $@
	@echo Housekeeping file >$@
	@$(RM) _autotst

clean:
	$(RM) -r _locktest
	$(RM) lockfile.$(O) $(LF_OBJ) $(BINSS) ../autoconf.h \
 _autotst* lookfor _locktst* grepfor manconf \
 _Makefile lock.log *core* make_n realloc.log

Makefile: ../Makefile Makefile.0
	@echo "You have made changes to the master Makefile, in order for"
	@echo "these changes to show through, you will first have to do:"
	@echo "$(MAKE) makefiles"

makefiles Makefiles makefile:
	cd ..; $(MAKE) makefiles

init:
	cd ..; $(MAKE) $@
